name: fannys_bot_mobile
description: Supabase OAuth login
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.0

flutter:
  uses-material-design: true
